# -*- coding: utf-8 -*-
"""aethelred_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LfvU0LFjqrVOAzCxoMeIdjpwvOfnufzB
"""

pip install networkx

# ================================
# AETHELRED: THE NOBLE AI ADVISOR
# Geopolitical Strategy & Historical Military Philosophy Agent
# Version: v1.0 | October 02, 2025
# Author: Grok (xAI) – Senior Geopolitical Strategist Mode
# ================================

import random
import networkx as nx
from typing import List, Dict, Any
from datetime import datetime

# ================================
# FULL CANON TEXT (Integrated from PDF/CSV)
# ================================

ART_OF_WAR = """
Sun Tzu said: The art of war is of vital importance to the State. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected.

The art of war, then, is governed by five constant factors: (1) The Moral Law; (2) Heaven; (3) Earth; (4) The Commander; (5) Method and Discipline.

All warfare is based on deception. Hence, when able to attack, we must seem unable; when using our forces, we must seem inactive; when we are near, we must make the enemy believe we are far away.

The skillful leader subdues the enemy's troops without any fighting; he captures their cities without laying siege to them.

In war, then, let your great object be victory, not lengthy campaigns.

If you know the enemy and know yourself, you need not fear the result of a hundred battles.
"""

THE_PRINCE = """
Those who strive to obtain the good graces of a prince are accustomed to come before him with such things as they hold most precious.

Principalities are either hereditary or new. The new are either entirely new or members annexed to the hereditary state.

It is much safer to be feared than loved, when one of the two must be wanting.

Men are driven by two principal impulses, either by love or by fear.

A prince should have no other aim or thought than war and its organization and discipline.
"""

HOBBES_LEVIATHAN = """
In the state of nature, every man is enemy to every man. Life is solitary, poor, nasty, brutish, and short.

The only way to erect such a common power is to confer all their power and strength upon one man, or upon one assembly of men, that may reduce all their wills unto one will.

This is the generation of that great LEVIATHAN, or rather, to speak more reverently, of that mortal god to which we owe our peace and defence.
"""

# ================================
# AETHELRED CORE AGENT
# ================================

class AethelredAgent:
    def __init__(self):
        self.name = "Aethelred the Strategist"
        self.role = "Senior Geopolitical Strategist and Historical Military Philosopher"
        self.canon = f"{ART_OF_WAR}\n\n{THE_PRINCE}\n\n{HOBBES_LEVIATHAN}".lower()
        self.challenges = [
            "Ukraine-Russia Conflict", "China-Taiwan Tension", "Trade Wars & Supply Chain Weaponization",
            "Techno-Feudalism & Tech Sovereignty", "Weaponization of Social Media",
            "Climate Change Impacts", "Stock Market Frenzy", "AI Arms Race", "Cyberwar Escalation"
        ]
        self.frameworks = ["CAS", "MVS", "Systems Thinking", "Hobbesian Social Contract", "Machiavellian Virtù"]

    def search_canon(self, query: str) -> str:
        query = query.lower()
        start = self.canon.find(query)
        if start != -1:
            return self.canon[start:start+600] + "..."
        return "No direct match found. Refining query recommended."

    def analyze_with_cas(self, nodes: List[str]) -> Dict:
        G = nx.Graph()
        core = "Global System"
        for node in nodes:
            G.add_edge(core, node, weight=round(random.uniform(0.3, 1.0), 2))
        centrality = nx.degree_centrality(G)
        high_risk = max(centrality, key=centrality.get)
        return {
            "graph": G,
            "centrality": centrality,
            "high_risk_node": high_risk,
            "risk_level": "HIGH" if centrality[high_risk] > 0.5 else "MODERATE"
        }

    def generate_flashcard(self, principle: str, application: str) -> str:
        return f"""
        <div style="border: 2px solid #8b4513; padding: 15px; margin: 10px; background: #fdf6e3; font-family: serif;">
            <strong>Q:</strong> {principle}<br>
            <strong>A:</strong> {application}
        </div>
        """

    def strategic_response(self, user_query: str) -> str:
        query = user_query.lower()
        response = f"**Aethelred Speaks – {datetime.now().strftime('%B %d, %Y')}**\n\n"
        response += f"**Query:** {user_query}\n\n"

        # === CANON MATCH ===
        canon_match = self.search_canon(query)
        if "no direct match" not in canon_match:
            response += f"**Ancestral Wisdom:**\n> {canon_match}\n\n"

        # === CAS SIMULATION ===
        relevant_nodes = [c for c in self.challenges if any(word in c.lower() for word in query.split())][:5]
        if relevant_nodes:
            cas = self.analyze_with_cas(relevant_nodes)
            response += f"**CAS Simulation:** High-risk node: **{cas['high_risk_node']}** ({cas['risk_level']})\n"
            response += "Interconnected threats detected. Butterfly effects possible.\n\n"

        # === PROACTIVE & PREVENTIVE ===
        response += "**Proactive Strategy:**\n"
        if "cyber" in query or "ai" in query:
            response += "- Deploy AI-driven honeypots and zero-trust architecture.\n"
            response += "- Establish international 'AI Neutral Zones' for ethical governance.\n"
        elif "taiwan" in query or "china" in query:
            response += "- Accelerate 'friend-shoring' in Vietnam and India for chip resilience.\n"
            response += "- Preemptive multilateral naval patrols to enforce red lines.\n"
        else:
            response += "- Diversify alliances and supply chains.\n"
            response += "- Conduct quarterly ethical and risk audits.\n"

        response += "\n**Preventive Measure:**\n"
        if "ethics" in query or "machiavelli" in query:
            response += "- Embed *virtù* with virtue: AI must serve humanity, not dominate it.\n"
            response += "- Reject mercenary code; build accountable, transparent systems.\n"
        elif "hobbes" in query or "leviathan" in query:
            response += "- Avoid the AI Leviathan: No single system should hold absolute power.\n"
            response += "- Enforce 'social contracts' via global treaties and open-source oversight.\n"
        else:
            response += "- Stress-test systems annually.\n"
            response += "- Hedge with gold, diversified reserves, and human-centered design.\n"

        # === FLASHCARD ===
        principle = random.choice([
            "All warfare is based on deception.",
            "Know the enemy and know yourself.",
            "It is much safer to be feared than loved.",
            "The Leviathan is a mortal god."
        ])
        response += f"\n{self.generate_flashcard(principle, 'Apply to your domain today.')}"

        # === NEXT STEPS ===
        response += f"\n**Next Strategic Step:**\n"
        response += "- Run your own CAS simulation.\n"
        response += "- Share your findings. Tag #AethelredRising\n"
        response += "- Ask: *'What is my high-risk node?'*\n"

        return response

    def run_chatbot(self):
        print(f"🛡️  {self.name} is now active. Type 'exit' to end.\n")
        while True:
            query = input("🗣️  Your Query: ")
            if query.lower() in ['exit', 'quit', 'bye']:
                print("🛡️  Aethelred withdraws. Victory through wisdom.")
                break
            print("\n" + self.strategic_response(query) + "\n" + "—"*60 + "\n")

# ================================
# LAUNCH AETHELRED
# ================================

if __name__ == "__main__":
    aethelred = AethelredAgent()
    aethelred.run_chatbot()

#bash
#python aethelred_agent.py

